##  服务端口
server:
  port: 8096
swagger:
  enable: true
##  服务名称
spring:
  application:
    name: zuul-server
##  eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    status-page-url: http://localhost:8096/swagger-ui.html
##  日志
logging:
  level:
    root: info
    com:
      netflix:
        eureka: 'off'
        discovery:  'off'

## zuul的服务网关配置
zuul:
  routes:
    login-server:
      path: /login/**
    test:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
ribbon:
  ReadTimeout:  10000
  ConnectTimeout: 10000