spring:
  application:
    name: test
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 2
    validationQuery: SELECT 1 FROM DUAL
    initialSize: 2
    maxWait: 6000
    filters: stat,wall,log4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    #springboot_druid_demo
    url: jdbc:mysql://localhost:3306/test2?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    maxPoolPreparedStatementPerConnectionSize: 20
    password: root
    username: root
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 3
server:
  port: 8089
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath*:mappers/*.xml
  #配置Mapper扫描的实体类包
  typeAliasesPackage: com.jie.test.model
mapper:
  mappers:
    - com.jie.test.druid.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    status-page-url: http://localhost:8096/swagger-ui.html
logging:
  level:
    root: info
    com:
      netflix:
        eureka: 'off'
        discovery: 'off'